#!/bin/sh
#
# Close IRCUT
#


start() {
	printf "Close IRCUT........"
	# 导出GPIO
	echo 104 > /sys/class/gpio/export
	echo 114 > /sys/class/gpio/export
	# 设置输出
	echo out > /sys/class/gpio/gpio104/direction
	echo out > /sys/class/gpio/gpio114/direction
	# 关闭IRCUT
	echo 0 > /sys/class/gpio/gpio104/value
	echo 0 > /sys/class/gpio/gpio114/value
}

stop() {
	printf "IRCUT stop.........."
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
