#!/bin/sh

start() {
    echo "Starting antares..."
    #Ethernet interface (Only needed for SC1725V)
    #ifconfig eth0 up
    #ifconfig eth0 192.168.9.6

    #SSH
    #Check here for authorized_keys and id_rsa files exist
    if [ ! -f /root/.ssh/authorized_keys ] || [ ! -f /root/.ssh/id_rsa ]
    then
        #Create .ssh directory
        mkdir -p /root/.ssh
        #Copy files
        cp /data/ssh/authorized_keys /root/.ssh/
        cp /data/ssh/id_rsa /root/.ssh/
        #Set permissions
        chmod 700 /root/.ssh
        chmod 600 /root/.ssh/authorized_keys
        chmod 600 /root/.ssh/id_rsa
    fi
    /etc/init.d/sshd start

    #Switch to USB-A (Only needed for SC1725V)
    #echo 412 > /sys/class/gpio/export
    #echo out > /sys/class/gpio/gpio412/direction
    #echo 1 > /sys/class/gpio/gpio412/value

    #Install the required modules for the USB modem and PPP
    insmod /lib/modules/4.9.191/usbserial.ko
    insmod /lib/modules/4.9.191/usb_wwan.ko
    insmod /lib/modules/4.9.191/option.ko
    insmod /lib/modules/4.9.191/slhc.ko
    insmod /lib/modules/4.9.191/ppp_generic.ko
    insmod /lib/modules/4.9.191/crc-ccitt.ko
    insmod /lib/modules/4.9.191/ppp_async.ko

    #Install the required module for the accelerometer
    # insmod /lib/modules/4.9.191/industrialio.ko
    # insmod /lib/modules/4.9.191/kfifo_buf.ko
    # insmod /lib/modules/4.9.191/industrialio-triggered-buffer.ko
    # insmod /lib/modules/4.9.191/st_sensors.ko
    # insmod /lib/modules/4.9.191/st_sensors_i2c.ko
    # insmod /lib/modules/4.9.191/st_accel.ko
    # insmod /lib/modules/4.9.191/st_accel_i2c.ko

    #Install the required module for the one-wire interface
    insmod /lib/modules/4.9.191/wire.ko
    insmod /lib/modules/4.9.191/ds2482.ko
    insmod /lib/modules/4.9.191/w1_therm.ko
    echo 0 > /sys/bus/w1/devices/w1_bus_master1/w1_master_pullup

    #Start Logging
    #Check here if the log file exists
     if [ ! -f /data/log/messages ]; then
        #Create log directory
        mkdir -p /data/log
        #Create the file
        touch /data/log/messages
    fi
    start-stop-daemon -b -S -x /sbin/syslogd -p /var/run/syslogd.pid -- -n -O /data/log/messages -s 256

    #Export and set GPIOs
    #Modem Power control
    echo 9 > /sys/class/gpio/export
    echo out > /sys/class/gpio/gpio9/direction
    echo 1 > /sys/class/gpio/gpio9/value

    #Modem Power ON/OFF control
    echo 132 > /sys/class/gpio/export
    echo out > /sys/class/gpio/gpio132/direction

    #Modem SIM disconnection control
    echo 8 > /sys/class/gpio/export
    echo out > /sys/class/gpio/gpio8/direction

    #Modem USB Enumeration control
    #echo 131 > /sys/class/gpio/export
    #echo out > /sys/class/gpio/gpio131/direction

    #Modem Reset control
    echo 139 > /sys/class/gpio/export
    echo out > /sys/class/gpio/gpio139/direction

    #Battery charging status
    echo 128 > /sys/class/gpio/export
    echo in > /sys/class/gpio/gpio128/direction
    echo 133 > /sys/class/gpio/export
    echo in > /sys/class/gpio/gpio133/direction

    #Power Rails monitoring
    echo 130 > /sys/class/gpio/export
    echo in > /sys/class/gpio/gpio130/direction
    echo 136 > /sys/class/gpio/export
    echo in > /sys/class/gpio/gpio136/direction

    #Microcontroller attention pin
    echo 137 > /sys/class/gpio/export
    echo in > /sys/class/gpio/gpio137/direction

    #LEDs YELLOW(161), GREEN(164), RED(166)
    echo 161 > /sys/class/gpio/export
    echo out > /sys/class/gpio/gpio161/direction
    echo 164 > /sys/class/gpio/export
    echo out > /sys/class/gpio/gpio164/direction
    echo 166 > /sys/class/gpio/export
    echo out > /sys/class/gpio/gpio166/direction

    #Accelerometer interrupt pins INT2(163), INT1(224)
    echo 163 > /sys/class/gpio/export
    echo in > /sys/class/gpio/gpio163/direction
    echo 224 > /sys/class/gpio/export
    echo in > /sys/class/gpio/gpio224/direction

    #USB External device detection
    echo 237 > /sys/class/gpio/export
    echo in > /sys/class/gpio/gpio237/direction

    #Start Antares application
    if [ -f /usr/bin/antares ]; then
        echo "Starting Antares application..."
        /usr/bin/antares &
    else
        echo "Antares application not found!"
    fi
}

stop() {
    echo "Stopping antares..."
    #Stop Antares application
    killall antares
    start-stop-daemon -K -q -p /var/run/syslogd.pid
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit $?
