#!/bin/sh
#
# Start wifi_deamon....
#

start() {
	#xr829 xr819s
	insmod /lib/modules/4.9.191/xradio_mac.ko
	insmod /lib/modules/4.9.191/xradio_core.ko
	insmod /lib/modules/4.9.191/xradio_wlan.ko

	#xr806
	#insmod /lib/modules/4.9.191/xr806.ko

      	printf "Starting wifi_deamon....: "
	wifi_deamon
	sleep 2
	wifi -o sta
	
	/usr/bin/bt_test -p gatt-server
}

stop() {
	printf "Stopping wifi_deamon: "
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
