########### paramter (ref to tulip_cedarx.conf)############
[parameter]
pcm_file_path = "/usr/share/startup.wav"
pcm_sample_rate = 48000
pcm_channel_cnt = 2
pcm_bit_width = 16
pcm_frame_size = 1024
ao_volume = 95
log_level = 0
